### ISSUE TITLE
Incorrect version in Docker image

### ISSUE THREAD

**Issue by atipugin** [valeriansaliou/sonic#104]
I've just pulled Docker image tagged v1.1.9 and noticed that actual version of sonic inside container is 1.1.8:

<img width="473" alt="Screenshot 2019-04-02 at 01 48 33" src="https://user-images.githubusercontent.com/281812/55364486-77785a00-54e9-11e9-902b-ff00ecde47c0.png">

**Comment by valeriansaliou** [comment]
Ah snap! Mistake from my end when I built it.

This is because v1.1.9 could not be pushed to Crates due to the rocksdb dependency being sourced from a Git URL while we wait a version bump from the original project.

As the Dockerfile uses Crates to install Sonic, it sourced the previous version; 1.1.9 could not be pushed there for the moment.

**Comment by valeriansaliou** [comment]
Closing this, as it will be auto-resolved in next release.
