### ISSUE TITLE
Is there a way to filter objects from the index?

### ISSUE THREAD

**Issue by ppshobi** [valeriansaliou/sonic#105]
So far I understand that sonic can be used for auto-suggestions but is there a way to apply filter/facets on the objects?

**Comment by valeriansaliou** [comment]
Hi there! As far as I understand your question, no there’s no way to do it at the moment.

Can you explain a bit your use case / needs?

**Comment by ppshobi** [comment]
I was wondering if I could use it instead of Algolia.

**Comment by pims** [comment]
I'm also quite interested in a filtering option, for instance to exclude documents containing some words.

**Comment by sairam** [comment]
@valeriansaliou 

I have a similar use case, we use Solr (ElasticSearch/Algolia offer similar solutions) as access control as well as search capability. In order to show data for a user, they should only access documents they have access. 

Or in a traditional ecommerce setting, when you want to filter into specific categories, we should not show data/products from other categories.

Let me know if you'd like any other information on the use case

**Comment by valeriansaliou** [comment]
You'd use buckets for categorization. That's what they're built for.

You'd have eg.:

- collection = products
- buckets = phones, tablets, laptops, (etc.)

**Comment by perzanko** [comment]
And to extend @valeriansaliou answer. You can create nested buckets as well:
```
phones
phones:apple
phones:apple:iphonex
phones:apple:iphone8
```

Anyway, remember that this is only a reference. To get the real data, you need to make another query, e.g. SQL
