### ISSUE TITLE
Ability to disable lexer for a command

### ISSUE THREAD

**Issue by pims** [valeriansaliou/sonic#108]
I'd love to be able to specify _words_ like `#type=user` without having the tokenizer attempt to split/tokenize them.

Would it be possible at insert/query time to specify that some words – maybe starting with `#`) – don't go through the text processing pipeline?

It would be extremely helpful for us to start replacing parts of elasticsearch with sonic.

What do you think?

**Comment by valeriansaliou** [comment]
Hi!

Yes, that's a requirement I'm starting to see for a lot of Sonic users. What I'm thinking about is add an optional argument to QUERY and PUSH commands to be able to disable stopwords removal. Eg. `LEXER(normalize)` and `LEXER(clean)` in order to select lexing mode, with a default on `clean`, while `normalize` would only ensure words are normalized (lower case, accented chars removal, etc.) but none would get removed.

Would that do?

**Comment by pims** [comment]
That would definitely help. My usecase is a little bit different though. I was hoping to be able to tag a document by adding `this was a great game category:basketball team_id:gsw` and benefit from normalize and clean but have the tags be left intact a PUSH time.

At query time, benefit from spelling correction on all words except for tags.

So I could send queries like “graet team_id:gsw” and have exact match on the tag but partial/typo match on every other word (with or without stop words)

Does this make sense?
Maybe I’m trying to use Sonic for something it wasn’t designed for, but quick filtering of documents is very important for us.
Currently using ES for this, but it’s performing poorly.

**Comment by valeriansaliou** [comment]
Ah, I see what you mean. This would be a bit beyond scope regarding the philosophy of Sonic, which is to keep things as simple as possible.

Otherwise you could push the text you want the lexing to be done on first, and then push the attributes with lexing disabled (with the to-be LEXER command modifier). As a PUSH command can add text to a new or existing object in Sonic, you could simply do this in a 2-steps operation.

Now on, regarding search, you could also perform a search with lexing disabled, and you'll be all set.

Would that do?

**Comment by pims** [comment]
Yes, that should work. 👍🏼

**Comment by valeriansaliou** [comment]
Hello @pims !

I confirm that the ability to disable lexer in QUERY and PUSH commands has been implemented in 2497d6c5f23cda8cc7979cbdc9102dc9aa198f18 via the existing `LANG()` query modifier. Simply pass `LANG(none)` to `QUERY` or `PUSH` commands, and this will force the lexer to behave as in normalize-only mode, and not clean-and-normalize. This will effectively ensure no word gets eluded by the stopwords system.

**Comment by pims** [comment]
Wonderful, merci!
