### ISSUE TITLE
Faster bulk insertion?

### ISSUE THREAD

**Issue by yjh0502** [valeriansaliou/sonic#132]
I have moderate-sized collection (\~20M record, \~10GB es index), and I'm trying to load the data into sonic. In my environment bulk insertion rate caps on 2k\~4k insertions/seconds. I tried to improve the insertion rate with multiple insertion jobs, but it seems that there's an internal lock which serializes all insertions. I also tried `eatmydata`, but the task is CPU-bound so it didn't work.

Is there any way to improve the insertion rate?

**Comment by yjh0502** [comment]
Here are some quick fixes to improve the performance:

 - use optimized `rocksdb` build: related to https://github.com/rust-rocksdb/rust-rocksdb/pull/167. slow CRC operation takes significant CPU time.
 - specify `lang` options: If lang option does not specified, sonic uses `whatlang` to detect a language, which is not that cheap.
 - batter config: disable rocksdb compression, larger write buffer size, ...

[1] https://gist.github.com/yjh0502/75c7b4945bf629b790dad42cc6c6ef4c

**Comment by valeriansaliou** [comment]
Thanks for the details on how you managed to get better performance out of Sonic.

Regarding:

1. Lang: yes, that's normal, ngrams are not cheap, which is why this extra `lang` parameter was added.
2. Compression: there is a trade-off, indeed. I'd recommend keeping compression ON as once ingested, data is much more compact and search is still fast enough.
3. Larger write buffer size: I'm keeping the default one to 16MB for the reason that by default, RocksDB on-disk WAL will soon be disabled, and will be all in-memory. Which means the write buffer should be small enough to minimize loss while recovering from crashes, as to perform more frequent disk synchronizations to SST. You're still free to momentarily increase this write buffer to a much larger value while importing, and lower it afterwards.
