### ISSUE TITLE
Integration test suite

### ISSUE THREAD

**Issue by vilunov** [valeriansaliou/sonic#133]
I see that Sonic is providing its own TCP protocol for control and document ingestion and queries and reference implementations of clients for Javascript and PHP. Testing of such protocol often involves running the server and some kind of reference client against each other. I propose we develop a similar testing procedure for Sonic using the server and a testing JS-script using the reference client implementation. Besides the protocol testing, we could do some sanity checks regarding the indexing and retrieval procedures.

One of the similar cases I've encountered is https://github.com/tower-rs/tower-grpc/. They run automated tests according to the official reference server implementation and test suite.

**Comment by vilunov** [comment]
On a related note, are there benchmarks showing high performance increase of a custom protocol over binary protocol frameworks such as gRPC?

**Comment by valeriansaliou** [comment]
Hello! That's an interesting idea, yes. I'd definitely accept any PR going in that direction regarding testing the Sonic Channel protocol.

On your second question, there's no benchmark at the protocol level at the moment. Sonic Channel, which is a text protocol, provides the advantage of being simple to implement for developers in client libraries — which is why I did not want to go for a binary protocol. Regarding the performance impact of that choice, I have seen that it was minimal in practice as you would need such a scale that would overwhelm all your database / store threads before pushing the protocol to its limit.

**Comment by vilunov** [comment]
Hello again, so I started some work in that direction: https://github.com/vilunov/sonic/commit/64f5b54ac52d20e43c825e0650b187a0cfe32abe

An example of CI pipeline could be seen here: https://travis-ci.org/vilunov/sonic/builds/533808124

The idea is to have a Node.js script using your protocol implementation to send queries to a running server instance. Right now it does nothing except connecting and pinging the server. This seems like an easy to maintain test suite to me, but I'm not sure whether it should be located in the same repo, as it also could be considered as a test suite for the client library.

I'm not making a PR until we decide whether such approach is fine and I have more tests running.

**Comment by valeriansaliou** [comment]
Hi @vilunov ; is there any update / progress on this? Anything I can review in order to integrate it to the main Sonic repository? Thanks!

**Comment by vilunov** [comment]
Hi @valeriansaliou, sorry for being absent, I had some unexpected issues to deal with. I'll continue with this soon

**Comment by valeriansaliou** [comment]
This has been integrated to Sonic in PR #154
