### ISSUE TITLE
No results when the keyword is part of the indexed term

### ISSUE THREAD

**Issue by funkfreakout** [valeriansaliou/sonic#166]
Guessing I ingest the object key in this way (I am currently using the php-client [Psonic](https://github.com/ppshobi/psonic))
`$ingest->push($collection, $bucket, $object_key, "Search Index");`

I am getting results on the search when the keywords are _search_, _index_, _search term_ ... or any combination of the characters of the search term above, always that is taking the start of the word. I mean, it will return the object key if I use "sea" but not if I use "earc". But I saw you can manage to do that on [Crisp Helpdesk](https://help.crisp.chat/en/). Am I supposed to set any specific configuration to be able to do it?

**Comment by valeriansaliou** [comment]
Hello! That's quite normal, as Sonic does not search by end-of-word. It's quite able to correct a mistyped end-of-word if the word is long-enough, as the Levenshtein distance that's allowed is higher (ie. mistaken characters, removed, added or different).

The word "search" is not long-enough to be corrected, thus Sonic does not find anything for "earch" as it does not allow any mistake to be made to enable the fuzzy-searching mode.

That's why. With Crisp Helpdesk, we use a fallback super-fuzzy search from a crossed MySQL database, with a simple WHERE LIKE %word%

**Comment by funkfreakout** [comment]
Hi! Sorry for not responding earlier, I have been very busy these past days. Thank you for your answer. To be honest I found that recently on one of the closed issues of the repository so I implemented something similar so it adapted to the needs I have. Thank you again.

**Comment by RemiBardon** [comment]
To anyone finding this in the future, I must mention this is no longer true. I don’t know when exactly it has been addressed, but it’s not a problem anymore. I just added a test, it passes:

```rs
test_ingest_then_query!("Search Index", [
    ("search", true),
    ("earch", true),
]);
```

(`true` means it returns a match)
