### ISSUE TITLE
Question: How to search multiple buckets in a collection?

### ISSUE THREAD

**Issue by daamsie** [valeriansaliou/sonic#198]
I'm playing around with this to use for a forum search tool. I would like some filtering options on the search though. At a most basic level, I could probably be happy with a search by subforum. 

So for example, I'd have a collection called "forumthreads" and multiple buckets in there called "forumthreads:Asia", "forumthreads:Europe", etc.. 

I'd like people to be able to search for their phrase inside all "forumthreads" buckets or just inside the "forumthreads:Europe" bucket. 

This does not seem possible though I feel like it should be. I'm using the Node.js client to test this software.

**Comment by valeriansaliou** [comment]
Hello!

It's not possible to organize buckets into super-buckets, that's right. That was not part of the requirements for which I built Sonic, hence this was not implemented.

What I would do in that case, is to search each bucket separately for the collection, and aggregate the results as to generate a "all" virtual bucket in your code. Or, otherwise, I'd create a "all" bucket in Sonic, and push all index contents there, as well as in their sub-bucket (this would double the data stored in Sonic, though).

**Comment by daamsie** [comment]
Thanks for the response. I suspected as much. While I do like the speed and simplicity of Sonic, I think for now there's just too many things missing to use in my project. I'll keep an eye on it though :)
