### ISSUE TITLE
so is this project dead?

### ISSUE THREAD

**Issue by kendofriendo** [valeriansaliou/sonic#327]
No updates since June, and the links to the example sites don't work. And it appears that Crisp has replaced Sonic with some useless AI?

**Comment by valeriansaliou** [comment]
It’s not dead, we are still using it at Crisp for search. Therefore it’s still being maintained. Since it’s stable at the moment and we don’t need more from Sonic I am not adding new features.

Useless AI: it’s just not comparable to traditional search. People look for instant answers and AI is the only way we can provide such reworded answers to users. It’s actually quite appreciated by users.
