### ISSUE TITLE
FLUSHO should also pop removed terms from FST

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/sonic#58]
If the term is not bound to any IID after removal from KV (as done in POP).

**Comment by valeriansaliou** [comment]
Unfortunately that's not possible, as all terms are hashed in KV. No way to trace it back to the original words in FST.

**Comment by VadymGidulian** [comment]
Hello,
First of all, thank you for this awesome project! I love it!

Does it mean that whenever possible it's better to use pop?

As I see it:
I have two posts:
```
PUSH posts default 1 "abc def"
PUSH posts default 2 "abc ghi"
```
I want to remove the first one.

If I'll do
```
FLUSHO posts default 1
```
then
```
SUGGEST posts default "a" => ["abc"]
SUGGEST posts default "d" => ["def"]
SUGGEST posts default "g" => ["ghi"]
```

And if I'll do
```
POP posts default 1 "abc def"
FLUSHO posts default 1 // Do I need this?
```
then
```
SUGGEST posts default "a" => ["abc"]
SUGGEST posts default "d" => []
SUGGEST posts default "g" => ["ghi"]
```
Am I right?

**Comment by valeriansaliou** [comment]
Hello there! The SUGGEST command is not fetching its data from the search index, but rather the graph of words (FST), from which AFAIK removed object words are not popped.

**Comment by VadymGidulian** [comment]
Yes, I understand.

I'll add a bit of context to my question.
Suppose a user wrote a post containing NSFW content/words, which are now indexed.
If the user will delete this post, NSFW words will remain in suggestions, that is most likely unwanted in some situations.

From the issue title I thought there's a way to remove words from FST.
_(I am not a Rust developer, the following may have no sense and be completely wrong)_
So I found the function that maybe does this
https://github.com/valeriansaliou/sonic/blob/b8bf28b38d3fdd13b497fb0da2b5baccb4670b81/src/store/fst.rs#L1096
which seems to be used during `POP`
https://github.com/valeriansaliou/sonic/blob/b8bf28b38d3fdd13b497fb0da2b5baccb4670b81/src/executor/pop.rs#L105

So I thought, there is a way to remove words from FST.

---

Well, actually in some cases words indeed are removed from FST, but sometimes they aren't.
I did some [tests](https://github.com/valeriansaliou/sonic/files/6062150/sonic.js.txt) that describe the expected behavior and the actual (details are in the attached file). Here are the results:
```
> jest -i sonic.js
Sonic
  2 posts
    ✓ Initial state
    ✓ POP 1 "abc"
    ✓ POP 1 "def"
    ✕ POP 1 "abc"; POP 1 "def"
    ✕ POP 1 "abc"; CONSOLIDATE; POP 1 "def"
    ✓ POP 1 "def"; POP 1 "abc"
    ✓ POP 1 "def"; CONSOLIDATE; POP 1 "abc"
    ✕ POP 1 "abc def"
    ✕ POP 1 "def abc"
    ✕ FLUSHO 1
    ✕ POP 1 "abc"; POP 1 "def"; FLUSHO 1
    ✕ POP 1 "abc"; CONSOLIDATE; POP 1 "def"; CONSOLIDATE; FLUSHO 1
    ✓ POP 1 "def"; POP 1 "abc"; FLUSHO 1
    ✓ POP 1 "def"; CONSOLIDATE; POP 1 "abc"; CONSOLIDATE; FLUSHO 1
    ✕ POP 1 "abc def"; FLUSHO 1
    ✕ POP 1 "abc def"; CONSOLIDATE; FLUSHO 1
    ✕ POP 1 "def abc"; FLUSHO 1
    ✕ POP 1 "def abc"; CONSOLIDATE; FLUSHO 1
```
I duplicated tests with added consolidations between steps in case if it may have any impact (clear caches, restructure data, etc.). Also, there's consolidation as the last step in all tests (not reflected in the tests' names).

**Comment by valeriansaliou** [comment]
Ah, you're indeed right, it's done for POP operations (it's 2+ years I've been implementing this, sorry for my bad memory!).

You could also easily check the FLUSHO code to ensure this is done there as well, but I'm not sure.

**Comment by VadymGidulian** [comment]
I don't see any work with FST in this file https://github.com/valeriansaliou/sonic/blob/master/src/executor/flusho.rs. Looks like you concluded this is not possible.
Though it does happen in `FLUSHC` and `FLUSHB`, but it's clear why - a whole collection/bucket is being removed.

But regarding the behavior of `POP`, could you please shed a light on my tests' results? Is this a bug or a sequence of actions leading to the impossibility to pop specific words from FST?
These two are especially strange, as for me, because I consider them equivalent:
```
✓ POP 1 "def"; POP 1 "abc"
✕ POP 1 "def abc"
```
